### PR TITLE
Create Natalie Lukac

### PR DESCRIPTION
**Pull request by natalielukac**

### CODE REVIEW

**Comment by natalielukac** [comment]
[Iterative Development.Paper Airplanes.pptx](https://github.com/skimedic/cincydeliverpresentations/files/3477500/Iterative.Development.Paper.Airplanes.pptx)

**Comment by natalielukac** [comment]
Here is my presentation!

**Comment by skimedic** [comment]
I added the file into the 2019 directory for you. Thanks!

**Comment by natalielukac** [comment]
Thanks Phil!

**Pull request merged**
